### PR TITLE
Created croesus-1mid-4man.txt

### PR DESCRIPTION
**Pull request by SalteaRS**
1mid 4man is the most optimal with duo slightly behind it.
this also has a mobility guide for each role to get around their node.

### CODE REVIEW

**Comment by SalteaRS** [comment]
> @SalteaRS is the mobility guide universal? ie. could it be put in the general croesus guide and mentioned in 1mid?
> 
> I noticed there is one section for 2:23 surge from tip I assume that is the only 1mid specific movement.
> 
> I might make minor style changes to make all the croesus guides look the same afterwards

it is a universal thing that could be used across all of croesus guides yeah.
the 2:23 surge from tip is 1mid / 2mid specific as in both of them you should realistically be repairing your statue before mid

**Comment by Archken** [comment]
Should remove personal pronouns

**Comment by Toosday** [comment]
Was busy the past couple days, I will take a look at this over the weekend, do some embed work then accept the PR :D

**Comment by Toosday** [comment]
sorry i couldn't get to this earlier, other task took a lot longer than i anticipated :')
i will try to make time for this asap

**Pull request merged**
