### PR TITLE
#Mechanics and #Ability-information changes

### PR DESCRIPTION
**Pull request by rsnDming**
+ Solo flanking section. 

- Boss Center & AoE ===> NPC Centers & AoE, major redesign
- Flanking Angle Determination ---> Facing and Position Determination, major redesign
+ All flanking 
- Manual Spellcasting ---> Refurbished.
- DBA
- BD updated

### CODE REVIEW

**Comment by Archken** [comment]
the minor changes outside of styling fixes i recall making are:
• When talking about wm getting slow, specified it was 2h
• Added omni and surge and blitz to the list of things slowed at tile 5
• reformatted that section a bit so each style starts on its main bullet
• there was something in manual spellcasting that was weirdly phrased so i rephrased it
• stated defensive autos only give the auto is off cd (should be obvious but lol)
• changed stalling video to lucas (was a good excuse to)
• changed the damage table in sgb to the image table used in the command
• changed vorago TC thing to specify that p3/p5 can be timed doing this 17t from crack heal tick, not just TS P5
there was probably a couple other things that i am forgetting, i was more focused on fixing all styling errors i could see so i forgot to note down changes i made

**Comment by Archken** [comment]
also can you make note of everything else you changed too, even if its just reformatting

**Comment by rsnDming** [comment]
- Solo flanking section added detailing the 3 major cases, and how to perform. Other cases exist but maybe for advanced (forced blocking).
- Boss Center & AoE section rewritten into NPC Center & AoE. SGB portion is supposed to lead from this.
- Flanking Angle Determination ---> Facing and Position Determination, major redesign. Previous itteration explained how it might happen, but now we have what is actually happening as well as why.
- Added flanking subsection to the above section due to Flanking being an exception to the rule of Flanking Angle determination.
- Manual Spellcasting ---> Updated it to use higher tiers than t92. Added Emerlad aurora in potential uses. Clarified the difference b/w the autocasted spell and the one manually chosen
- DBA rewrtiten and incorporated Archken's feedback
- BD updated the image, took Chi's opinion. Made sense to both of us but I think it should be done by someone else. Moved this section up closer to the facing section.
- SGB portion, rewritten some parts, added deathspore arrows, touched abit on blocking.

**Comment by rsnDming** [comment]
Removed SGB from NPC coords abilities

**Comment by Archken** [comment]
did some formatting fixes to #mechanics, as well as the following minor changes:
1) removed the link to queueing wiki page in last tick of zerk interactions (its unrelated and eventually that wiki page is being ported anyway)

2) added back step 1 to determining where arrows 2-5 of sgb (i.e., picking the npc centre (and how its picked), as just assuming they have read the npc centre thingy is not ideal imo

3) added the note back to bosses for sgb size (as it explains why the bosses listed are listed, because assuming they read the sgb writeup before that is also not ideal imo)

**Pull request merged**
