### PR TITLE
Updated mage-brid guide to include gwd3

### PR DESCRIPTION
**Pull request by Brain-iiac**
this guide is post magma nerf and post Omni/fsoa release. it has the meta starts that are used for the fastest duo kills rightnow.
better example kills will be added soon.

### CODE REVIEW

**Comment by Brain-iiac** [comment]
do i correct the style errors myself and request again or is it done differently?

**Comment by Archken** [comment]
> do i correct the style errors myself and request again or is it done differently?

You just directly edit the file in this PR and commit the changes to this PR to fix the style issues

You can easily get to the file from the PR going through:
image
image
and then just commit the changes to the same branch when done (it should be the default thing it tries to commit to)

**Comment by Brain-iiac** [comment]
All styling issues have been fixed.

**Comment by Brain-iiac** [comment]
is there anything missing or what is this request awaiting right now?

**Comment by Archken** [comment]
> is there anything missing or what is this request awaiting right now?

Someone mentioned they want to look over it before doing any merging, but I do not know when that will occur sadly

**Comment by Trackandxc** [comment]
made a new channel rather than updating current channel

**Pull request closed without merging**
