### PR TITLE
add explanation on how to 5taa with revo on

### PR DESCRIPTION
**Pull request by HightDetal**

### CODE REVIEW

**Comment by Archken** [comment]
I feel like you could word:

>  With revolution active you will have to use <:cease:864235458464186418> to prevent revo from activating. Click on your target 4t after casting your ability to force an auto attack then use your next ability 1t after.

better, because it is not until the example that you are told when to cease.
Maybe something like:

> With Revolution active, you will have to use Cease [cease emoji] after you cast the ability before the auto. Then, click on your target 4t after said ability's cast to get the auto attack, and then use your next ability 1t after that."

just some idea, probably better way to phrase it but cannot think of it currently

**Comment by jgabrielius** [comment]
@Archken What do you think about this?:

> With Revolution active, after casting fastest non-channeled ability, you will have to use Cease <cease> (or off by other means) before Revolution triggers your next ability. Then, click on your target 4t after initial cast (after your abilities flash) to force an auto attack. Follow it up with your next ability 1t later.

**Comment by HightDetal** [comment]
@Archken What do you think about this?:

> With Revolution active, after casting fastest non-channeled ability, you will have to use Cease (or off by other means) before Revolution triggers your next ability. Then, click on your target 4t after initial cast (after your abilities flash) to force an auto attack. Follow it up with your next ability 1t later.

**Comment by Archken** [comment]
@HightDetal 
Sounds fine, just fix up the English a bit + a tad of rewording, so:

> With Revolution active, after casting a fastest non-channeled ability, you will have to use Cease [CEASE EMOJI HERE] (or off by other means) before Revolution triggers your next ability. Then, click on your target 4t after your initial ability casts, which is 1t after the GCD ends (i.e., when your ability bar flashes), to force an auto attack. Follow it up with your next ability 1t after the auto.

think it sounds a bit better and more clear about timings of everything, what do you think?

**Comment by HightDetal** [comment]
@Archken sounds good! Updated PR with the change

**Pull request merged**
