### PR TITLE
Add FSOA usage command

### PR DESCRIPTION
**Pull request by inferiumRS3**
First commit and attempt to create an embed for basic FSOA usage, as there have been quite a few people asking for just some kind of general idea to follow. Welcome any feedback on my formatting or suggested changes to the "sample basic rotation".

### CODE REVIEW

**Comment by inferiumRS3** [comment]
Not quite sure what I'm missing for the embed being invalid. Any tips?

**Comment by Archken** [comment]
This is really long for a command, would fit more in the channel itself and then a more bite-sized version for the command which then references the channel for more details

**Comment by nolanslade** [comment]
@Archken Hmm. Do I have access to the bot test channel? Thanks for the feedback - to be honest I was worried about that too. When I get access to that channel I'll take a peek what you've got, then shorten this one up and incorporate anything you've got there.

Then I can move more of the meat of this command to the DPM channel

**Comment by inferiumRS3** [comment]
@Archken Hmm. Do I have access to the bot test channel? Thanks for the feedback - to be honest I was worried about the length too. When I get access to that channel, I'll take a peek at what you have and then condense this PR. Then I can move the meat of it over to DPM advice instead.

**Pull request merged**
