### PR TITLE
added duo rots

### PR DESCRIPTION
**Pull request by SalteaRS**
added a duo method

### CODE REVIEW

**Comment by SalteaRS** [comment]
will be updating this again soon with a surge rot which is better.

**Comment by txj-xyz** [comment]
Hi is this ready?

**Comment by Ferroric** [comment]
Think there is 1 or 2 style guide things

**Comment by inferiumRS3** [comment]
fixed some styling but needs proper preset and breakdown

**Comment by inferiumRS3** [comment]
also we should really just make a ROTS basic guide and remove a lot of the stuff from the original guide

**Comment by inferiumRS3** [comment]
i made rots basic and linked this to it, still needs preset and probably more cutting down

**Comment by SalteaRS** [comment]
with the melee buffs on Monday, there's now an even better rot for duo. will update it with those soon

**Pull request merged**
