### PR TITLE
rots section added (separated 4man and duo, as solo guide coming soon)

### PR DESCRIPTION
**Pull request by SalteaRS**
# PvME Change Submission
Thank you for helping maintain our resources! Below is a quick sanity checklist that helps make sure we can keep track of what is changing. Please fill it out :)

## Sanity Checks
- [x] - The title of this pull request clearly describes the change I would like to make.
- [x] - If there are multiple changes in this pull request, they are all related.
- [x] - I have tried to write clear a commit message(s) that describes the changes I made.

### CODE REVIEW

**Comment by SalteaRS** [comment]
Ahrim fix on Monday so can merge whenever

**Comment by SalteaRS** [comment]
all done :)

**Comment by Ferroric** [comment]
This is epic, will build these guys a home when I'm home if others are unable to

**Comment by Ferroric** [comment]
^small typo fix

**Pull request merged**
