### PR TITLE
Update Boss School Discord Invite URL

### PR DESCRIPTION
**Pull request by txj-xyz**

### CODE REVIEW

**Comment by inferiumRS3** [comment]
@txj-xyz Are you sure this is a perma-link?

**Comment by txj-xyz** [comment]
@inferiumRS3 Yes, 100% here is the request data for the Invite itself.
```json
{
  "code": "88ru2vd",
  "type": 0,
  "expires_at": null,
  "guild": {
    "id": "183966276706631680",
    "name": "Boss School",
    "splash": "95e1c2f1bd329a01b4f0a1a82dfa3c85",
    "banner": "0e1ff5c22e1c055042556b770ef122d5",
    "description": "Our objective is to help you fully appreciate RuneScape's combat by teaching & supporting the community.",
    "icon": "a_919673a55f1a61705f0b74f8136c0454",
    "features": [
      "NEW_THREAD_PERMISSIONS",
      "THREE_DAY_THREAD_ARCHIVE",
      "SEVEN_DAY_THREAD_ARCHIVE",
      "PRIVATE_THREADS",
      "VANITY_URL",
      "BANNER",
      "WELCOME_SCREEN_ENABLED",
      "MEMBER_PROFILES",
      "NEWS",
      "ANIMATED_BANNER",
      "INVITE_SPLASH",
      "ROLE_ICONS",
      "ANIMATED_ICON",
      "COMMUNITY"
    ],
    "verification_level": 1,
    "vanity_url_code": null,
    "premium_subscription_count": 14,
    "welcome_screen": {
      "description": "Our objective is to help you fully appreciate RuneScape's combat by teaching & supporting you regardless of previous experience.",
      "welcome_channels": [
        {
          "channel_id": "427266076343140363",
          "description": "Who we are!",
          "emoji_id": null,
          "emoji_name": "👋"
        },
        {
          "channel_id": "946847429767094283",
          "description": "Our rules and code of conduct.",
          "emoji_id": null,
          "emoji_name": "✅"
        },
        {
          "channel_id": "941725611792138281",
          "description": "Have a question? We have answers!",
          "emoji_id": null,
          "emoji_name": "❔"
        },
        {
          "channel_id": "923983311095873596",
          "description": "Get ready for our sessions!",
          "emoji_id": "924009556776980601",
          "emoji_name": "combat"
        },
        {
          "channel_id": "183966276706631680",
          "description": "Come say hi!",
          "emoji_id": null,
          "emoji_name": "🗨️"
        }
      ]
    },
    "nsfw": false,
    "nsfw_level": 0
  },
  "channel": {
    "id": "427266076343140363",
    "name": "welcome",
    "type": 0
  },
  "inviter": {
    "id": "269233963460067340",
    "username": "Manu",
    "avatar": "c1b80c191327fa722fe522a4ee10e4c5",
    "avatar_decoration": null,
    "discriminator": "1943",
    "public_flags": 0
  }
}
```

**Comment by txj-xyz** [comment]
`"expires_at": null,` = Infinite

**Comment by txj-xyz** [comment]
Invites can be checked at the `GET` endpoint for `https://discordapp.com/api/invite/code_here`

**Pull request merged**
